calculate all fit metrics with pastas.stats.metrics and fix pytest issues (#410)
* rename file

To prevent running when calling pytest (because of test in filename). plt.show() calls figure and pauses the pytest script.

* Remove fail test 21_signatures.ipynb

TypeError: set_ticks() got an unexpected keyword argument 'rotation'

* replace fit metrics by ones in stats library

* only give pandas.Series to pastas.stats.metrics

Co-authored-by: Raoul Collenteur <raoulcollenteur@gmail.com>